@graphql_url = http://localhost:8080/query

POST {{graphql_url}}
Content-Type: application/json
# Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

mutation {
  createUser(input: {username: "user1", password: "123"})
}

###
POST {{graphql_url}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(input: {username: "user1", password: "123"})
}

###
POST {{graphql_url}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  refreshToken(input: {token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTI3NzQyMjAsInVzZXJuYW1lIjoidXNlcjEifQ.wwDnOZp2vgwdKbG_Haiy2VL31pHwoCD3GFVUnJXaOuA"})
}

###
POST {{graphql_url}}
Content-Type: application/json
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTMwNTY5NjYsInVzZXJuYW1lIjoidXNlcjEifQ.UAxTkTwJn1y3TeEqOsGU_hAf3FLK3VqMmZyKSCpWacU"
X-REQUEST-TYPE: GraphQL

mutation {
  createLink(input: {title: "new link", address:"http://address.org"}){
    title,
    user{
      name
    }
    address
  }
}
