@graphql_url = http://localhost:8080/query

POST {{graphql_url}}
Content-Type: application/json
# Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

mutation {
  createUser(input: {username: "user1", password: "123"})
}

###
POST {{graphql_url}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  login(input: {username: "user1", password: "123"})
}

###
POST {{graphql_url}}
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTM0NDI3MTcsInVzZXJuYW1lIjoidXNlcjEifQ.gN13MOCtR5RBrzfPS96z10b-00qVpsjdVUbh0tBkwmw
X-REQUEST-TYPE: GraphQL

mutation {
  refreshToken(input: {token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTM0NDI3MTcsInVzZXJuYW1lIjoidXNlcjEifQ.gN13MOCtR5RBrzfPS96z10b-00qVpsjdVUbh0tBkwmw"
  })
}

###
POST {{graphql_url}}
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VybmFtZSI6InVzZXIxIiwiZXhwIjoxNjEzNDQ1NzAwfQ.8AlSgte3GgXJ-y7wGMm0zBTqnDTEid0dFPf6Q4M_4o0
X-REQUEST-TYPE: GraphQL

mutation {
  createLink(input: {title: "new link", address:"http://address.org"}){
    title,
    user{
      name
    }
    address
  }
}
